from enum import Enum


class StaticItemClasses:
    class Currency(Enum):
        TRANSMUTATION_SHARD = "transmutation-shard"
        CHANCE_SHARD = "chance-shard"
        REGAL_SHARD = "regal-shard"
        ARTIFICERS_SHARD = "artificers-shard"
        SCROLL_OF_WISDOM = "wisdom"
        ORB_OF_TRANSMUTATION = "transmute"
        ORB_OF_AUGMENTATION = "aug"
        ORB_OF_CHANCE = "chance"
        ORB_OF_ALCHEMY = "alch"
        CHAOS_ORB = "chaos"
        VAAL_ORB = "vaal"
        REGAL_ORB = "regal"
        EXALTED_ORB = "exalted"
        DIVINE_ORB = "divine"
        ORB_OF_ANNULMENT = "annul"
        ARTIFICERS_ORB = "artificers"
        FRACTURING_ORB = "fracturing-orb"
        MIRROR_OF_KALANDRA = "mirror"
        ARMOURERS_SCRAP = "scrap"
        BLACKSMITHS_WHETSTONE = "whetstone"
        ARCANISTS_ETCHER = "etcher"
        GLASSBLOWERS_BAUBLE = "bauble"
        GEMCUTTERS_PRISM = "gcp"

    class Fragments(Enum):
        BREACH_SPLINTER = "breach-splinter"
        BREACHSTONE = "breachstone"
        SIMULACRUM_SPLINTER = "simulacrum-splinter"
        SIMULACRUM = "simulacrum"
        AN_AUDIENCE_WITH_THE_KING = "an-audience-with-the-king"
        COWARDLY_FATE = "cowardly-fate"
        DEADLY_FATE = "deadly-fate"
        VICTORIOUS_FATE = "victorious-fate"
        ANCIENT_CRISIS_FRAGMENT = "ancient-crisis-fragment"
        FADED_CRISIS_FRAGMENT = "faded-crisis-fragment"
        WEATHERED_CRISIS_FRAGMENT = "weathered-crisis-fragment"

    class Runes(Enum):
        LESSER_DESERT_RUNE = "lesser-desert-rune"
        LESSER_GLACIAL_RUNE = "lesser-glacial-rune"
        LESSER_STORM_RUNE = "lesser-storm-rune"
        LESSER_IRON_RUNE = "lesser-iron-rune"
        LESSER_BODY_RUNE = "lesser-body-rune"
        LESSER_MIND_RUNE = "lesser-mind-rune"
        LESSER_REBIRTH_RUNE = "lesser-rebirth-rune"
        LESSER_INSPIRATION_RUNE = "lesser-inspiration-rune"
        LESSER_STONE_RUNE = "lesser-stone-rune"
        LESSER_VISION_RUNE = "lesser-vision-rune"
        DESERT_RUNE = "desert-rune"
        GLACIAL_RUNE = "glacial-rune"
        STORM_RUNE = "storm-rune"
        IRON_RUNE = "iron-rune"
        BODY_RUNE = "body-rune"
        MIND_RUNE = "mind-rune"
        REBIRTH_RUNE = "rebirth-rune"
        INSPIRATION_RUNE = "inspiration-rune"
        STONE_RUNE = "stone-rune"
        VISION_RUNE = "vision-rune"
        GREATER_DESERT_RUNE = "greater-desert-rune"
        GREATER_GLACIAL_RUNE = "greater-glacial-rune"
        GREATER_STORM_RUNE = "greater-storm-rune"
        GREATER_IRON_RUNE = "greater-iron-rune"
        GREATER_BODY_RUNE = "greater-body-rune"
        GREATER_MIND_RUNE = "greater-mind-rune"
        GREATER_REBIRTH_RUNE = "greater-rebirth-rune"
        GREATER_INSPIRATION_RUNE = "greater-inspiration-rune"
        GREATER_STONE_RUNE = "greater-stone-rune"
        GREATER_VISION_RUNE = "greater-vision-rune"
        GREATER_RUNE_OF_LEADERSHIP = "greater-rune-of-leadership"
        GREATER_RUNE_OF_TITHING = "greater-rune-of-tithing"
        GREATER_RUNE_OF_ALACRITY = "greater-rune-of-alacrity"
        GREATER_RUNE_OF_NOBILITY = "greater-rune-of-nobility"

    class Talismans(Enum):
        BEAR_TALISMAN = "bear-talisman"
        PRIMATE_TALISMAN = "primate-talisman"
        STAG_TALISMAN = "stag-talisman"
        BOAR_TALISMAN = "boar-talisman"
        SERPENT_TALISMAN = "serpent-talisman"
        WOLF_TALISMAN = "wolf-talisman"
        CAT_TALISMAN = "cat-talisman"
        OWL_TALISMAN = "owl-talisman"
        OX_TALISMAN = "ox-talisman"
        FOX_TALISMAN = "fox-talisman"
        RABBIT_TALISMAN = "rabbit-talisman"

    class Essences(Enum):
        ESSENCE_OF_THE_BODY = "essence-of-the-body"
        ESSENCE_OF_THE_MIND = "essence-of-the-mind"
        ESSENCE_OF_ENHANCEMENT = "essence-of-enhancement"
        ESSENCE_OF_TORMENT = "essence-of-torment"
        ESSENCE_OF_FLAMES = "essence-of-flames"
        ESSENCE_OF_ICE = "essence-of-ice"
        ESSENCE_OF_ELECTRICITY = "essence-of-electricity"
        ESSENCE_OF_RUIN = "essence-of-ruin"
        ESSENCE_OF_BATTLE = "essence-of-battle"
        ESSENCE_OF_SORCERY = "essence-of-sorcery"
        ESSENCE_OF_HASTE = "essence-of-haste"
        ESSENCE_OF_THE_INFINITE = "essence-of-the-infinite"
        GREATER_ESSENCE_OF_THE_BODY = "greater-essence-of-the-body"
        GREATER_ESSENCE_OF_THE_MIND = "greater-essence-of-the-mind"
        GREATER_ESSENCE_OF_ENHANCEMENT = "greater-essence-of-enhancement"
        GREATER_ESSENCE_OF_TORMENT = "greater-essence-of-torment"
        GREATER_ESSENCE_OF_FLAMES = "greater-essence-of-flames"
        GREATER_ESSENCE_OF_ICE = "greater-essence-of-ice"
        GREATER_ESSENCE_OF_ELECTRICITY = "greater-essence-of-electricity"
        GREATER_ESSENCE_OF_RUIN = "greater-essence-of-ruin"
        GREATER_ESSENCE_OF_BATTLE = "greater-essence-of-battle"
        GREATER_ESSENCE_OF_SORCERY = "greater-essence-of-sorcery"
        GREATER_ESSENCE_OF_HASTE = "greater-essence-of-haste"
        GREATER_ESSENCE_OF_THE_INFINITE = "greater-essence-of-the-infinite"
        ESSENCE_OF_HYSTERIA = "essence-of-hysteria"
        ESSENCE_OF_DELIRIUM = "essence-of-delirium"
        ESSENCE_OF_HORROR = "essence-of-horror"
        ESSENCE_OF_INSANITY = "essence-of-insanity"

    class Ultimatum(Enum):
        SOUL_CORE_OF_TACATI = "soul-core-of-tacati"
        SOUL_CORE_OF_OPILOTI = "soul-core-of-opiloti"
        SOUL_CORE_OF_JIQUANI = "soul-core-of-jiquani"
        SOUL_CORE_OF_ZALATL = "soul-core-of-zalatl"
        SOUL_CORE_OF_CITAQUALOTL = "soul-core-of-citaqualotl"
        SOUL_CORE_OF_PUHUARTE = "soul-core-of-puhuarte"
        SOUL_CORE_OF_TZAMOTO = "soul-core-of-tzamoto"
        SOUL_CORE_OF_XOPEC = "soul-core-of-xopec"
        SOUL_CORE_OF_AZCAPA = "soul-core-of-azcapa"
        SOUL_CORE_OF_TOPOTANTE = "soul-core-of-topotante"
        SOUL_CORE_OF_QUIPOLATL = "soul-core-of-quipolatl"
        SOUL_CORE_OF_TICABA = "soul-core-of-ticaba"
        SOUL_CORE_OF_ATMOHUA = "soul-core-of-atmohua"
        SOUL_CORE_OF_CHOLOTL = "soul-core-of-cholotl"
        SOUL_CORE_OF_ZANTIPI = "soul-core-of-zantipi"

    class Breachcatalyst(Enum):
        FLESH_CATALYST = "flesh-catalyst"
        NEURAL_CATALYST = "neural-catalyst"
        CARAPACE_CATALYST = "carapace-catalyst"
        UULNETOLS_CATALYST = "uul-netols-catalyst"
        XOPHS_CATALYST = "xophs-catalyst"
        TULS_CATALYST = "tuls-catalyst"
        ESHS_CATALYST = "eshs-catalyst"
        CHAYULAS_CATALYST = "chayulas-catalyst"
        REAVER_CATALYST = "reaver-catalyst"
        SIBILANT_CATALYST = "sibilant-catalyst"
        SKITTERING_CATALYST = "skittering-catalyst"
        ADAPTIVE_CATALYST = "adaptive-catalyst"

    class Expedition(Enum):
        EXOTIC_COINAGE = "exotic-coinage"
        BROKEN_CIRCLE_ARTIFACT = "broken-circle-artifact"
        BLACK_SCYTHE_ARTIFACT = "black-scythe-artifact"
        ORDER_ARTIFACT = "order-artifact"
        SUN_ARTIFACT = "sun-artifact"

    class Ritual(Enum):
        OMEN_OF_REFRESHMENT = "omen-of-refreshment"
        OMEN_OF_RESURGENCE = "omen-of-resurgence"
        OMEN_OF_AMELIORATION = "omen-of-amelioration"
        OMEN_OF_WHITTLING = "omen-of-whittling"
        OMEN_OF_SINISTRAL_ERASURE = "omen-of-sinistral-erasure"
        OMEN_OF_DEXTRAL_ERASURE = "omen-of-dextral-erasure"
        OMEN_OF_SINISTRAL_ALCHEMY = "omen-of-sinistral-alchemy"
        OMEN_OF_DEXTRAL_ALCHEMY = "omen-of-dextral-alchemy"
        OMEN_OF_SINISTRAL_CORONATION = "omen-of-sinistral-coronation"
        OMEN_OF_DEXTRAL_CORONATION = "omen-of-dextral-coronation"
        OMEN_OF_CORRUPTION = "omen-of-corruption"
        OMEN_OF_GREATER_EXALTATION = "omen-of-greater-exaltation"
        OMEN_OF_SINISTRAL_EXALTATION = "omen-of-sinistral-exaltation"
        OMEN_OF_DEXTRAL_EXALTATION = "omen-of-dextral-exaltation"
        OMEN_OF_GREATER_ANNULMENT = "omen-of-greater-annulment"
        OMEN_OF_SINISTRAL_ANNULMENT = "omen-of-sinistral-annulment"
        OMEN_OF_DEXTRAL_ANNULMENT = "omen-of-dextral-annulment"
        OMEN_OF_ANSWERED_PRAYERS = "omen-of-answered-prayers"
        OMEN_OF_THE_HUNT = "omen-of-the-hunt"
        OMEN_OF_REINFORCEMENTS = "omen-of-reinforcements"
        OMEN_OF_SECRET_COMPARTMENTS = "omen-of-secret-compartments"

    class Deliriuminstill(Enum):
        DISTILLED_IRE = "distilled-ire"
        DISTILLED_GUILT = "distilled-guilt"
        DISTILLED_GREED = "distilled-greed"
        DISTILLED_PARANOIA = "distilled-paranoia"
        DISTILLED_ENVY = "distilled-envy"
        DISTILLED_DISGUST = "distilled-disgust"
        DISTILLED_DESPAIR = "distilled-despair"
        DISTILLED_FEAR = "distilled-fear"
        DISTILLED_SUFFERING = "distilled-suffering"
        DISTILLED_ISOLATION = "distilled-isolation"

    class Waystones(Enum):
        WAYSTONE_TIER_ONE = "waystone-1"
        WAYSTONE_TIER_TWO = "waystone-2"
        WAYSTONE_TIER_THREE = "waystone-3"
        WAYSTONE_TIER_FOUR = "waystone-4"
        WAYSTONE_TIER_FIVE = "waystone-5"
        WAYSTONE_TIER_SIX = "waystone-6"
        WAYSTONE_TIER_SEVEN = "waystone-7"
        WAYSTONE_TIER_EIGHT = "waystone-8"
        WAYSTONE_TIER_NINE = "waystone-9"
        WAYSTONE_TIER_TEN = "waystone-10"
        WAYSTONE_TIER_ELEVEN = "waystone-11"
        WAYSTONE_TIER_TWELVE = "waystone-12"
        WAYSTONE_TIER_THIRTEEN = "waystone-13"
        WAYSTONE_TIER_FOURTEEN = "waystone-14"
        WAYSTONE_TIER_FIFTEEN = "waystone-15"
        WAYSTONE_TIER_SIXTEEN = "waystone-16"
        PRECURSOR_TABLET = "precursor-tablet"
        BREACH_PRECURSOR_TABLET = "breach-precursor-tablet"
        EXPEDITION_PRECURSOR_TABLET = "expedition-precursor-tablet"
        DELIRIUM_PRECURSOR_TABLET = "delirium-precursor-tablet"
        RITUAL_PRECURSOR_TABLET = "ritual-precursor-tablet"
        OVERSEER_PRECURSOR_TABLET = "overseer-precursor-tablet"

    class Vaultkeys(Enum):
        TWILIGHT_RELIQUARY_KEY = "twilight-reliquary-key"
        XESHTS_RELIQUARY_KEY = "xeshts-reliquary-key"
        THE_TRIALMASTERS_RELIQUARY_KEY = "the-trialmasters-reliquary-key"
        RITUALISTIC_RELIQUARY_KEY = "ritualistic-reliquary-key"
        TANGMAZUS_RELIQUARY_KEY = "tangmazus-reliquary-key"
        OLROTHS_RELIQUARY_KEY = "olroths-reliquary-key"
        THE_ARBITERS_RELIQUARY_KEY = "the-arbiters-reliquary-key"
        ZAROKHS_RELIQUARY_KEY_AGAINST_THE_DARKNESS = "against-the-darkness"
        ZAROKHS_RELIQUARY_KEY_SANDSTORM_VISAGE = "sandstorm-visage"
        ZAROKHS_RELIQUARY_KEY_BLESSED_BONDS = "blessed-bonds"
        ZAROKHS_RELIQUARY_KEY_SEKHEMAS_RESOLVE = "sekhemas-resolve"
        ZAROKHS_RELIQUARY_KEY_TEMPORALIS = "temporalis"
